### ISSUE TITLE
Also works on MacOS & Prusa Mini

### ISSUE THREAD

**Issue by RAMilewski** [awabom/3dprint#1]
Works fine on Original Prusa Mini with Prusa Slicer 2.5 on MacOS.
Path to Python3 on my system is /usr/local/bin/python3.

Thank you! This problem has been annoying me since switched to Prusa Slicer.

**Comment by awabom** [comment]
Glad you found it useful :) Let's hope a real fix makes it into 2.6

**Comment by Morcegolas** [comment]
Hello, I added this to my Post-processing scripts:
`"/usr/local/bin/python3" "/Users/myusername/Downloads/FixM600.py"`

How do I know it worked? It gave no errors, but I also tried:
 `/usr/local/bin/python3 /Users/myusername/Downloads/FixM600.py` and it also gave no errors...
