### ISSUE TITLE
Post Processing script?

### ISSUE THREAD

**Issue by chasedown26** [awabom/3dprint#7]
This is my first time using orca, I have an SV04 and was linked to this from the facebook group.
I imported the profiles, but when I go to slice i get a post processing script doesnt exist error.

**Comment by awabom** [comment]
The installation is almost the same as for PrusaSlicer, check here: https://github.com/awabom/3dprint/tree/main/PrusaSlicer-SV04#installation

And do installation steps 1-3 :)
