### ISSUE TITLE
How Add profile

### ISSUE THREAD

**Issue by Hindryckx** [awabom/3dprint#9]
Hello, I would like to use ocra for my sv04.  Where do I put the files?  Under orcaslicer/recources/profiles/sovol/ filament,machine,process ?  Then import into orca, that doesn't work.  should I import 1 file at a time or more, order?  Thank you in advance.

**Comment by awabom** [comment]
Follow the instructions for the PrusaSlicer profiles: https://github.com/awabom/3dprint/tree/main/PrusaSlicer-SV04/

Except, step 4, the files should be copied to 'OrcaSlicer' instead.
